import Head from 'next/head'
import Nav from './Nav'
import NavItem from './NavItem'
import List from './List.js'
import ListItem from './ListItem.js'



const praticien ='https://elsan.void.fr/fr/jsonapi/node/elsan_praticien'
export const getStaticProps = async() => {
  const res = await fetch(praticien)
  const object = await res.json()
  return{
    props:{
      object
    }
  }
}
export default function Home({object}) {
  
  return (
    <div >
      <Head>
        <title>Void dev Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className="mt-20 text-center">
          <h1 className="text-3xl text-current">Prendre RDV avec un(e) spécialiste à proximité de France</h1>
          <h2 className="text-2xl">Trouver un spécialiste au sein des cliniques ELSAN</h2>
        </div>
        <div className="flex justify-center divide-y divide-slate-100">
          <div className="w-2/5">
            <Nav>
              <NavItem href="/index.js" className="bg-slate-400" isActive>Spécialiste</NavItem>
              <NavItem href="/">Etablissements</NavItem>
            </Nav>
            <List >
              {object.data.map((item) => (
                <ListItem key={item.id} item={item.attributes} />
              ))}
            </List>
          </div>
        </div>
      </main>
    </div>
  )
}
